MARVELMIND_NAME := marvelmind

MARVELMIND_PATH := $(EXTERNAL_DIR)/$(MARVELMIND_NAME)
MARVELMIND_SRC_DIR := $(MARVELMIND_PATH)/src

MARVELMIND_SO_TARGET := $(LIB_DIR)/lib$(MARVELMIND_NAME).so

EXT_LIB_TARGETS += $(MARVELMIND_SO_TARGET)
EXT_LIBS += -l$(MARVELMIND_NAME)
EXT_CFLAGS += -I$(MARVELMIND_SRC_DIR)

$(MARVELMIND_SO_TARGET): $(MARVELMIND_SRC_DIR)/marvelmind.c
	@mkdir -p $(LIB_DIR)
	@echo "SO EXT  $< -> $@"
	@$(CC) $(CFLAGS) -fPIC -shared $< -o $@