# Build configuration for Mosquitto

MOSQ_NAME := mosquitto
MOSQ_PATH := $(EXTERNAL_DIR)/$(MOSQ_NAME)

MOSQ_SONAME      := lib$(MOSQ_NAME).so.1
MOSQ_LINKER_NAME := lib$(MOSQ_NAME).so

MOSQ_TARGET_SONAME := $(LIB_DIR)/$(MOSQ_SONAME)
MOSQ_TARGET_LINK   := $(LIB_DIR)/$(MOSQ_LINKER_NAME)

EXT_LIB_TARGETS += $(MOSQ_TARGET_SONAME) $(MOSQ_TARGET_LINK)

EXT_LIBS   += -l$(MOSQ_NAME)
EXT_CFLAGS += -I$(MOSQ_PATH)/include


$(MOSQ_TARGET_SONAME):
	@echo "SO EXT $(MOSQ_NAME)..."
	@$(MAKE) -C $(MOSQ_PATH) binary DIRS="lib" WITH_SHARED_LIBRARIES=yes WITH_STATIC_LIBRARIES=no DOCS=no WITH_CJSON=no
	@mkdir -p $(LIB_DIR)
	@cp $(MOSQ_PATH)/lib/$(MOSQ_SONAME) $(MOSQ_TARGET_SONAME)

$(MOSQ_TARGET_LINK): $(MOSQ_TARGET_SONAME)
	@echo "LN   $(MOSQ_LINKER_NAME) -> $(MOSQ_SONAME)"
	@cd $(LIB_DIR) && ln -sf $(MOSQ_SONAME) $(MOSQ_LINKER_NAME)


.PHONY: clean-$(MOSQ_NAME)

clean-$(MOSQ_NAME):
	@echo "CLEAN $(MOSQ_NAME)..."
	@$(MAKE) -C $(MOSQ_PATH) clean